spring:
  application:
    name: 09_ToolCalling

  ai:
    ollama:
      chat:
        model: qwen3
    openai:
      api-key: ${MyVerySecretChatGptKey}

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
