spring:
  application:
    name: 10_MCPServer

  ai:
    mcp:
      server:
        type: sync
    openai:
      api-key: ${MyVerySecretChatGptKey}
  mvc:
    log-request-details: true

logging:
    level:
      org:
        springframework:
          ai: DEBUG
          web: DEBUG


server:
  error:
    include-message: always
  port: 7070