spring:
  application:
    name: RAG

  ai:
    openai:
      api-key: ${MyVerySecretChatGptKey}

logging:
    level:
      org:
        springframework:
          ai:
            chat:
              client:
                advisor: DEBUG
          web: DEBUG