spring:
  application:
    name: 04_Test

  ai:
#    ollama:
#      chat:
#        model: qwen3
    openai:
      api-key: ${MyVerySecretChatGptKey}

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
