spring:
  application:
    name: RAG

  ai:
    openai:
      api-key: ${MyVerySecretChatGptKey}
      chat:
        model: gpt-5


  datasource:
    url: jdbc:hsqldb:file:db/orderDb
    username: sa
    password:
  jpa:
    generate-ddl: true
    properties:
      jakarta:
        persistence:
          sql-load-script-source: import.sql
          schema-generation:
            database:
              action: drop-and-create
logging:
  level:
    org:
      springframework:
        ai: DEBUG
        web: DEBUG
    org.springframework.ai.openai.OpenAiEmbeddingModel: TRACE