spring:
  application:
    name: MultiModality_Moderation

  ai:
#    ollama:
#      chat:
#        model: gemma3
    openai:
      api-key: ${MyVerySecretChatGptKey}
#      image:
#        options:
#          model:

  mvc:
    log-request-details: true

logging:
    level:
      org:
        springframework: DEBUG
#          ai: DEBUG
#          web: DEBUG

server:
  error:
    include-message: always