spring:
  application:
    name: ErsteAnwendung

  ai:
#    ollama:
#      chat:
#        model: gemma3
#      init:
#        pull-model-strategy: when_missing
    openai:
      api-key: ${MyVerySecretChatGptKey}

  mvc:
    log-request-details: true

logging:
    level:
      org:
        springframework:
          ai:
            chat:
              client:
                advisor: DEBUG