spring:
  application:
    name: 08_ChatMemory_VectorStoreAdvisor

  ai:
    openai:
      api-key: ${MyVerySecretChatGptKey}
      chat:
        model: gpt-5

  mvc:
    log-request-details: true

logging:
    level:
      org:
        springframework:
          ai: DEBUG
          web: DEBUG
      org.springframework.ai.openai.OpenAiEmbeddingModel: TRACE

server:
  error:
    include-message: always