spring:
  application:
    name: RAG

  ai:
    openai:
      api-key: ${MyVerySecretChatGptKey}
      chat:
        model: gpt-5

logging:
  level:
    org:
      springframework:
        ai: DEBUG
        web: DEBUG
    org.springframework.ai.openai.OpenAiEmbeddingModel: TRACE