<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.thorben.janssen.spring.ai</groupId>
        <artifactId>parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
	<artifactId>10_MCPClient</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>10_MCPClient</name>
	<description>Backend demo project for Spring AI</description>
    <dependencies>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-mcp-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.thorben.janssen.spring.ai</groupId>
            <artifactId>99_Shared</artifactId>
        </dependency>
    </dependencies>
</project>
