spring:
  application:
    name: 04_Test_Testcontainers

  ai:
    openai:
      api-key: ${MyVerySecretChatGptKey}
    ollama:
      chat:
        model: qwen3

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
