spring:
  application:
    name: Prompting_Rollen

  ai:
#    ollama:
#      chat:
#        model: gemma3
    openai:
      api-key: ${MyVerySecretChatGptKey}
      chat:
        model: gpt-5
        max-completion-tokens: 1500
        temperature: 1

  # Docker-based models using OpenAI API
#    openai:
#      api-key: ignored
#      base-url: http://localhost:12434/engines
#      chat:
#        options:
#          model: ai/gemma3

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG