spring:
  application:
    name: Exp_ModerationAdvisor

  ai:
#    ollama:
#      chat:
#        model: gemma3

    openai:
      api-key: ${MyVerySecretChatGptKey}
    model:
      moderation:
        options:
          model: omni-moderation-latest

  mvc:
    log-request-details: true

logging:
    level:
      org:
        springframework:
          ai: DEBUG
          web: DEBUG

server:
  error:
    include-message: always